### ISSUE TITLE
Many of the sites listed as "supported" do not work with pastebinit

### ISSUE THREAD

**Issue by pvshvp-oss** [skorokithakis/pastebinit#5]
The sites that worked with `pastebinit` are:
1. dpaste.com
2. paste.ubuntu.com
3. slexy.org
4. sprunge.us

The following did not work with `pastebinit`:
1. fpaste.org
2. p.defau.lt
3. paste.debian.net
4. paste.openstack.org
5. paste.pound-python.org
6. paste.ubuntu.org.cn
7. paste2.org
8. pastebin.com

```
[user@user-desktop temp]$ pastebinit -l
Supported pastebins:
- dpaste.com
- fpaste.org
- p.defau.lt
- paste.debian.net
- paste.openstack.org
- paste.pound-python.org
- paste.ubuntu.com
- paste.ubuntu.org.cn
- paste2.org
- pastebin.com
- slexy.org
- sprunge.us
[user@user-desktop temp]$ pastebinit -i test.txt -b dpaste.com
http://dpaste.com//98YTGW298
[user@user-desktop temp]$ pastebinit -i test.txt -b fpaste.org
Failed to contact the server: <urlopen error timed out>
[user@user-desktop temp]$ pastebinit -i test.txt -b p.defau.lt
https://p.defau.lt/new.html
[user@user-desktop temp]$ pastebinit -i test.txt -b paste.debian.net
https://paste.debian.net/
[user@user-desktop temp]$ pastebinit -i test.txt -b paste.openstack.org
Traceback (most recent call last):
  File "/usr/bin/pastebinit", line 412, in <module>
    params = bytes(json.dumps(params), encoding='US-ASCII')
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[user@user-desktop temp]$ pastebinit -i test.txt -b paste.pound-python.org
http://paste.pound-python.org/
[user@user-desktop temp]$ pastebinit -i test.txt -b paste.ubuntu.com
https://paste.ubuntu.com/p/kRcBry95mC/
[user@user-desktop temp]$ pastebinit -i test.txt -b paste.ubuntu.org.cn
https://paste.ubuntu.org.cn/
[user@user-desktop temp]$ pastebinit -i test.txt -b paste2.org
https://paste2.org/
[user@user-desktop temp]$ pastebinit -i test.txt -b pastebin.com
Failed to contact the server: HTTP Error 405: Method Not Allowed
[user@user-desktop temp]$ pastebinit -i test.txt -b slexy.org
https://slexy.org/view/s2RUjWXg0d
[user@user-desktop temp]$ pastebinit -i test.txt -b sprunge.us
http://sprunge.us/C4mU0q
[user@user-desktop temp]$ 
```

**Comment by yucongo** [comment]
Only `dpaste.com` and `sprunge.us` work now it seems. For example
```bash
curl -s https://jsonplaceholder.typicode.com/todos/1 | pastebinit -b dpaste.com
```
```
http://dpaste.com//66R7TH9T2  # or similar
```

**Comment by skorokithakis** [comment]
Hm, yeah... I didn't write this utility, unfortunately, it's just a code dump.

**Comment by skorokithakis** [comment]
I use https://www.pastery.net/, which has the `bakeit` utility for pasting.
